from em.formalgeo.configuration import GeometricConfiguration
from em.formalgeo.tools import load_json, parse_gdl, debug_execute, draw_gpl


def test_gpl():
    parsed_gdl = parse_gdl(load_json('../../../data/gdl-xiaokai.json'))

    draw_gpl(
        parsed_gdl['Relations']['PerpendicularBisector']['algebraic_forms'],
        filename='algebraic_forms'
    )

    draw_gpl(
        parsed_gdl['Theorems']['tangent_between_line_and_circle_determination_perpendicular']['premises'],
        filename='premises'
    )


def test1():
    parsed_gdl = parse_gdl(load_json('../../../data/gdl-xiaokai.json'))

    gc = GeometricConfiguration(parsed_gdl=parsed_gdl)
    debug_execute(gc.construct, ['Point(A)&Point(B):FreePoint(A)&FreePoint(B)'])
    debug_execute(gc.construct, ['Point(C):PointLeftSegment(C,A,B)'])
    debug_execute(gc.construct, ['Line(a):PointOnLine(B,a)&PointOnLine(C,a)'])
    debug_execute(gc.construct, ['Line(b):PointOnLine(A,b)&PointOnLine(C,b)'])
    debug_execute(gc.construct, ['Line(c):PointOnLine(A,c)&PointOnLine(B,c)'])
    debug_execute(gc.construct, ['Line(x):PointOnLine(A,x)&EqualAngle(b,x,x,c)'])
    debug_execute(gc.construct, ['Line(y):PointOnLine(B,y)&EqualAngle(c,y,y,a)'])
    debug_execute(gc.construct, ['Point(O):PointOnLine(O,x)&PointOnLine(O,y)'])
    debug_execute(gc.construct, ['Line(z):PointOnLine(C,z)&PointOnLine(O,z)'])
    debug_execute(gc.construct, ['Circle(Ω):PointOnCircle(A,Ω)&PointOnCircle(B,Ω)&PointOnCircle(C,Ω)'])

    gc.draw_gc()

    debug_execute(gc.set_goal, ['AngleBisector(C,z,a,b)'])

    debug_execute(gc.decompose, ['angle_bisector_determination_distance_equal'])
    debug_execute(gc.decompose, ['equal_distance_point_to_line_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_distance_point_to_line_property_algebraic'])

    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal'])
    debug_execute(gc.apply, ['angle_bisector_property_distance_equal'])

    gc.show_gc()
    gc.draw_sg()


def test2():
    parsed_gdl = parse_gdl(load_json('../../../data/gdl-xiaokai.json'))

    gc = GeometricConfiguration(parsed_gdl=parsed_gdl)

    debug_execute(gc.construct, ['Point(A)&Point(B):FreePoint(A)&FreePoint(B)'])
    debug_execute(gc.construct, ['Point(C):PointLeftSegment(C,A,B)'])
    debug_execute(gc.construct, ['Circle(Ω):PointOnCircle(A,Ω)&PointOnCircle(B,Ω)&PointOnCircle(C,Ω)'])
    debug_execute(gc.construct, ['Line(a):PointOnLine(A,a)&PointOnLine(B,a)'])
    debug_execute(gc.construct, ['Line(b):PointOnLine(B,b)&PointOnLine(C,b)'])
    debug_execute(gc.construct, ['Line(c):PointOnLine(C,c)&ParallelBetweenLine(c,a)'])
    debug_execute(gc.construct, ['Line(d):PointOnLine(A,d)&ParallelBetweenLine(b,d)'])
    debug_execute(gc.construct, ['Point(D):PointOnLine(D,d)&PointOnLine(D,c)'])
    debug_execute(gc.construct, ['Line(l):PointOnLine(A,l)&PointOnLine(C,l)'])
    gc.draw_gc()

    debug_execute(gc.set_goal, ['EqualDistancePointToPoint(A,B,C,D)&EqualDistancePointToPoint(D,A,B,C)'])

    debug_execute(gc.apply, ['parallel_property_multiple_forms'])
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])

    debug_execute(gc.decompose, ['congruent_triangle_property_line_equal'])
    debug_execute(gc.decompose, ['congruent_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['congruent_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['congruent_triangle_determination_asa'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])

    gc.show_gc()
    gc.draw_sg()


def test_imo_2025_p2_gc():
    """ constructions: 42, theorems: 204"""
    parsed_gdl = parse_gdl(load_json('../../../data/gdl-xiaokai.json'))

    gc = GeometricConfiguration(parsed_gdl=parsed_gdl, random_seed=19)

    debug_execute(gc.construct, ['Circle(Γ)&Circle(Ω):IntersectBetweenCircle(Ω,Γ)&G(Sub(Γ.rc,Ω.rc))'])
    debug_execute(gc.construct, ['Point(M):CenterOfCircle(M,Ω)'])
    debug_execute(gc.construct, ['Point(N):CenterOfCircle(N,Γ)'])
    debug_execute(gc.construct, ['Point(A):PointOnCircle(A,Ω)&PointOnCircle(A,Γ)&PointLeftSegment(A,N,M)'])
    debug_execute(gc.construct, ['Point(B):PointOnCircle(B,Ω)&PointOnCircle(B,Γ)&PointLeftSegment(B,M,N)'])
    debug_execute(gc.construct, ['Line(a):PointOnLine(M,a)&PointOnLine(N,a)'])
    debug_execute(gc.construct, ['Point(C):PointOnLine(C,a)&PointOnCircle(C,Ω)&PointLeftSegment(C,A,B)'])
    debug_execute(gc.construct, ['Point(D):PointOnLine(D,a)&PointOnCircle(D,Γ)&PointLeftSegment(D,B,A)'])
    debug_execute(gc.construct, ['Line(c):PointOnLine(A,c)&PointOnLine(D,c)'])
    debug_execute(gc.construct, ['Line(d):PointOnLine(A,d)&PointOnLine(C,d)'])
    debug_execute(gc.construct, ['Point(P):CircumcenterOfTriangle(P,C,d,A,c,D,a)'])
    debug_execute(gc.construct, ['Line(p):PointOnLine(A,p)&PointOnLine(P,p)'])
    debug_execute(gc.construct, ['Point(E):PointOnLine(E,p)&PointOnCircle(E,Ω)&~SamePoint(E,A)'])
    debug_execute(gc.construct, ['Point(F):PointOnLine(F,p)&PointOnCircle(F,Γ)&~SamePoint(F,A)'])
    debug_execute(gc.construct, ['Line(n):PointOnLine(P,n)&PointOnLine(M,n)'])
    debug_execute(gc.construct, ['Line(m):PointOnLine(P,m)&PointOnLine(N,m)'])
    debug_execute(gc.construct, ['Point(H):OrthocenterOfTriangle(H,P,n,M,a,N,m)'])
    debug_execute(gc.construct, ['Line(f):PointOnLine(B,f)&PointOnLine(E,f)'])
    debug_execute(gc.construct, ['Line(e):PointOnLine(B,e)&PointOnLine(F,e)'])
    debug_execute(gc.construct, ['Circle(Φ):CircumcircleOfTriangle(Φ,B,f,E,p,F,e)'])

    debug_execute(gc.construct, ['Line(x):PointOnLine(M,x)&PointOnLine(E,x)'])  # aux
    debug_execute(gc.construct, ['Line(y):PointOnLine(N,y)&PointOnLine(F,y)'])
    debug_execute(gc.construct, ['Point(T):PointOnLine(T,x)&PointOnLine(T,y)'])
    debug_execute(gc.construct, ['Line(t):PointOnLine(H,t)&PointOnLine(T,t)'])
    debug_execute(gc.construct, ['Circle(Δ):CircumcircleOfTriangle(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.construct, ['Line(g):PointOnLine(P,g)&PointOnLine(C,g)'])
    debug_execute(gc.construct, ['Line(h):PointOnLine(P,h)&PointOnLine(D,h)'])
    debug_execute(gc.construct, ['Line(i):PointOnLine(M,i)&PointOnLine(H,i)'])
    debug_execute(gc.construct, ['Line(j):PointOnLine(N,j)&PointOnLine(H,j)'])
    debug_execute(gc.construct, ['Line(k):PointOnLine(A,k)&PointOnLine(M,k)'])
    debug_execute(gc.construct, ['Line(l):PointOnLine(A,l)&PointOnLine(N,l)'])
    debug_execute(gc.construct, ['Line(u):PointOnLine(B,u)&PointOnLine(C,u)'])
    debug_execute(gc.construct, ['Line(v):PointOnLine(A,v)&PointOnLine(B,v)'])
    debug_execute(gc.construct, ['Line(w):PointOnLine(B,w)&PointOnLine(D,w)'])
    debug_execute(gc.construct, ['Point(X):PointOnLine(X,n)&PointOnLine(X,d)'])
    debug_execute(gc.construct, ['Point(Y):PointOnLine(Y,m)&PointOnLine(Y,c)'])
    debug_execute(gc.construct, ['Point(G):CenterOfCircle(G,Φ)'])
    debug_execute(gc.construct, ['Line(b):PointOnLine(T,b)&PointOnLine(G,b)'])
    debug_execute(gc.construct, ['Point(Q):PointOnLine(Q,p)&PointOnLine(Q,b)'])
    debug_execute(gc.construct, ['Line(q):PointOnLine(F,q)&PointOnLine(G,q)'])
    debug_execute(gc.construct, ['Line(o):PointOnLine(E,o)&PointOnLine(G,o)'])
    debug_execute(gc.construct, ['Point(K):PointOnLine(K,v)&PointOnLine(K,a)'])

    debug_execute(gc.set_goal, ['ParallelBetweenLine(p,t)&TangentBetweenLineAndCircle(t,Φ)'])

    gc.draw_gc(scale=2)

    return gc


def test_imo_2025_p2_forward():
    gc = test_imo_2025_p2_gc()
    debug_execute(gc.apply, ['circumcenter_of_triangle_property_center_of_circle(P,Δ,C,d,A,c,D,a)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Δ,D,a,C,d,A,c)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Δ,P,C)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Δ,P,A)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Δ,P,D)'])

    # prove ∠gd = ∠dp
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(P,C,P,A)'])
    debug_execute(gc.apply, ['triangle_determination(P,g,C,d,A,p)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(P,g,C,d,A,p)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(P,g,C,d,A,p)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(g,d,d,p)'])

    # prove ∠pc = ∠ch
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(P,A,P,D)'])
    debug_execute(gc.apply, ['triangle_determination(P,p,A,c,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(P,p,A,c,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(P,p,A,c,D,h)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(p,c,c,h)'])

    # prove ∠ga = ∠ah
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(P,C,P,D)'])
    debug_execute(gc.apply, ['triangle_determination(P,g,C,a,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(P,g,C,a,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(P,g,C,a,D,h)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(g,a,a,h)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Ω,M,C)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Ω,M,A)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Ω,M,E)'])

    # prove ∠ad = ∠dk
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(M,C,M,A)'])
    debug_execute(gc.apply, ['triangle_determination(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(a,d,d,k)'])

    # prove ∠kp = ∠px
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(M,A,M,E)'])
    debug_execute(gc.apply, ['triangle_determination(M,k,A,p,E,x)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(M,k,A,p,E,x)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(M,k,A,p,E,x)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(k,p,p,x)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Γ,N,A)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Γ,N,D)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Γ,N,F)'])

    # prove ∠lc = ∠ca
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(N,A,N,D)'])
    debug_execute(gc.apply, ['triangle_determination(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(l,c,c,a)'])

    # prove ∠yp = ∠pl
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(N,F,N,A)'])
    debug_execute(gc.apply, ['triangle_determination(N,y,F,p,A,l)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(N,y,F,p,A,l)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(N,y,F,p,A,l)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(y,p,p,l)'])
    debug_execute(gc.apply, ['line_property_angle_addition(C,g,a,d)'])
    debug_execute(gc.apply, ['line_property_angle_addition(A,d,k,p)'])
    debug_execute(gc.apply, ['line_property_angle_addition(A,p,l,c)'])
    debug_execute(gc.apply, ['line_property_angle_addition(D,c,a,h)'])

    # prove y // k
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(y,p,k,p)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(y,k,p)'])

    # prove x // l
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,x)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,l)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(x,p,l,p)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(x,l,p)'])
    debug_execute(gc.apply, ['perpendicular_bisector_determination_center_line_and_common_chord(Ω,Γ,M,N,a,A,B,v)'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_perpendicular_between_line(a,v,A,B)'])

    # prove ∠fp = 2∠ad
    debug_execute(gc.apply, ['perpendicular_between_line_property_multiple_forms(a,v)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(a,v)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(v,a)'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_distance_equal(a,v,A,B,C)'])
    debug_execute(gc.apply, ['triangle_determination(C,d,A,v,B,u)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(C,d,A,v,B,u)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(C,d,A,v,B,u)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(d,v,v,u)'])
    debug_execute(gc.apply, ['triangle_determination(A,v,K,a,C,d)'])
    debug_execute(gc.apply, ['triangle_determination(B,u,C,a,K,v)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(A,v,K,a,C,d)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(B,u,C,a,K,v)'])
    debug_execute(gc.apply, ['line_property_angle_addition(C,u,a,d)'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_same_circle(Ω,B,C,A,E)'])
    debug_execute(gc.apply, ['concyclic_between_points_property_inscribed_angle_sum(B,u,C,d,A,p,E,f)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,f)'])

    # prove ∠pe = 2∠ca
    debug_execute(gc.apply, ['perpendicular_bisector_property_multiple_forms(a,v,A,B)'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_distance_equal(a,v,B,A,D)'])
    debug_execute(gc.apply, ['triangle_determination(D,w,B,v,A,c)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(D,w,B,v,A,c)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(D,w,B,v,A,c)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(w,v,v,c)'])
    debug_execute(gc.apply, ['triangle_determination(D,w,B,v,K,a)'])
    debug_execute(gc.apply, ['triangle_determination(D,a,K,v,A,c)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(D,w,B,v,K,a)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(D,a,K,v,A,c)'])
    debug_execute(gc.apply, ['line_property_angle_addition(D,c,a,w)'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_same_circle(Γ,B,A,D,F)'])
    debug_execute(gc.apply, ['concyclic_between_points_property_inscribed_angle_equal(B,w,A,c,D,e,F,p)'])

    # prove ∠ay = 2∠ad
    debug_execute(gc.apply, ['triangle_property_angle_sum(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,k)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(y,k,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(y,a,k,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,y)'])

    # prove ∠la = 2∠ca
    debug_execute(gc.apply, ['triangle_property_angle_sum(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,l)'])

    # prove ∠xy = 2∠ad + 2∠ca
    debug_execute(gc.apply, ['line_property_angle_addition(N,l,a,y)'])
    debug_execute(gc.apply, ['parallel_property_multiple_forms(x,l)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(l,x,y)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(l,y,x,y)'])

    # prove ∠ef + ∠xy = 180° (T on Φ)
    debug_execute(gc.apply, ['triangle_determination(F,e,B,f,E,p)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(F,e,B,f,E,p)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Φ,F,e,B,f,E,p)'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_inscribed_angle_sum(F,e,B,f,E,x,T,y)'])
    debug_execute(gc.apply, ['point_on_circle_determination_concyclic(Φ,F,B,E,T)'])

    # prove m ⊥ c
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(N,P,N,P)'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(A,N,D,N)'])
    debug_execute(gc.apply, ['triangle_determination(A,l,N,m,P,p)'])
    debug_execute(gc.apply, ['triangle_determination(D,h,P,m,N,a)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_sss(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(l,m,m,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(l,m)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(m,a)'])
    debug_execute(gc.apply, ['triangle_determination(Y,m,N,l,A,c)'])
    debug_execute(gc.apply, ['triangle_determination(Y,c,D,a,N,m)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(m,l,a,m)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_asa(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(N,l,A,c,Y,m,N,a,D,c,Y,m)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(A,c,Y,m,N,l,D,c,Y,m,N,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(c,m,m,c)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(m,c)'])

    # prove n ⊥ d
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(C,M,A,M)'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(M,P,M,P)'])
    debug_execute(gc.apply, ['triangle_determination(C,a,M,n,P,g)'])
    debug_execute(gc.apply, ['triangle_determination(A,p,P,n,M,k)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_sss(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(a,n,n,k)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,n)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(n,k)'])
    debug_execute(gc.apply, ['triangle_determination(X,n,M,a,C,d)'])
    debug_execute(gc.apply, ['triangle_determination(X,d,A,k,M,n)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(n,a,k,n)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_asa(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(M,a,C,d,X,n,M,k,A,d,X,n)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(C,d,X,n,M,a,A,d,X,n,M,k)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(d,n,n,d)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(n,d)'])

    # prove i // c
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_multiple_forms(H,P,n,M,a,N,m)'])
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_perpendicular(H,i,M,a,N,m,P,n)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(i,m)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(i,m,c,m)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(i,c,m)'])

    # prove ∠xi = ∠ia
    debug_execute(gc.apply, ['parallel_property_angle_equal(i,c,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(i,a,c,a)'])
    debug_execute(gc.apply, ['line_property_angle_addition(M,x,i,a)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(x,l,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(x,a,l,a)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(x,i,i,a)'])
    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal(M,i,x,a)'])

    # prove j // d
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_multiple_forms(H,M,a,N,m,P,n)'])
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_perpendicular(H,j,N,m,P,n,M,a)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(j,n)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(d,n,j,n)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(d,j,n)'])

    # prove ∠aj = ∠jy
    debug_execute(gc.apply, ['parallel_property_angle_equal(d,j,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(d,a,j,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,d)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,j)'])
    debug_execute(gc.apply, ['line_property_angle_addition(N,a,j,y)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(a,j,j,y)'])
    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal(N,j,a,y)'])

    # prove ∠yt = ∠tx
    debug_execute(gc.apply, ['triangle_determination(T,x,M,a,N,y)'])
    debug_execute(gc.apply, ['incenter_of_triangle_determination_angle_bisector(H,i,j,T,x,M,a,N,y)'])
    debug_execute(gc.apply, ['incenter_of_triangle_property_angle_bisector(H,t,T,x,M,a,N,y)'])
    debug_execute(gc.apply, ['angle_bisector_property_equal_angle(T,t,y,x)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(y,t,t,x)'])

    # prove t // p
    debug_execute(gc.apply, ['line_property_angle_addition(T,y,t,x)'])
    debug_execute(gc.apply, ['triangle_determination(F,p,E,x,T,y)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(F,p,E,x,T,y)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(y,x)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(t,x,p,x)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(t,p,x)'])
    debug_execute(gc.apply, ['parallel_property_multiple_forms(t,p)'])

    # prove b ⊥ p
    debug_execute(gc.apply, ['triangle_determination(G,q,F,p,Q,b)'])
    debug_execute(gc.apply, ['triangle_determination(G,b,Q,p,E,o)'])
    debug_execute(gc.apply, ['triangle_determination(G,q,F,p,E,o)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Φ,G,F)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Φ,G,E)'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(G,F,G,E)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(G,q,F,p,E,o)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(G,q,F,p,E,o)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(q,p,p,o)'])
    debug_execute(gc.apply, ['arc_property_central_angle_and_inscribed_angle(Φ,G,T,F,E,b,q,x,p)'])
    debug_execute(gc.apply, ['arc_property_central_angle_and_inscribed_angle(Φ,G,E,T,F,o,b,p,y)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(b,o)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(q,b)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(G,q,F,p,Q,b)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(G,b,Q,p,E,o)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,b)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(t,p,b)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(t,b,p,b)'])

    # prove t ⊥ p
    debug_execute(gc.apply, ['perpendicular_between_line_determination_angle(t,b)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_multiple_forms(t,b)'])
    debug_execute(gc.apply, ['tangent_between_line_and_circle_determination_perpendicular(Φ,G,b,T,t)'])


def test_imo_2025_p2_backward():
    gc = test_imo_2025_p2_gc()
    debug_execute(gc.decompose, ['tangent_between_line_and_circle_determination_perpendicular(Φ,G,b,T,t)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_multiple_forms(t,b)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_determination_angle(t,b)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(t,b,p,b)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(t,p,b)'])
    debug_execute(gc.decompose, ['parallel_property_multiple_forms(t,p)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(t,p,x)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(t,x,p,x)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(F,p,E,x,T,y)'])
    debug_execute(gc.decompose, ['triangle_determination(F,p,E,x,T,y)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(T,y,t,x)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(y,t,t,x)'])
    debug_execute(gc.decompose, ['angle_bisector_property_equal_angle(T,t,y,x)'])
    debug_execute(gc.decompose, ['incenter_of_triangle_property_angle_bisector(H,t,T,x,M,a,N,y)'])
    debug_execute(gc.decompose, ['incenter_of_triangle_determination_angle_bisector(H,i,j,T,x,M,a,N,y)'])
    debug_execute(gc.decompose, ['triangle_determination(T,x,M,a,N,y)'])
    debug_execute(gc.decompose, ['angle_bisector_determination_angle_equal(N,j,a,y)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(a,j,j,y)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(N,a,j,y)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,j)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(d,a,j,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(d,j,a)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(d,j,n)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(d,n,j,n)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(j,n)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_perpendicular(H,j,N,m,P,n,M,a)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_multiple_forms(H,M,a,N,m,P,n)'])
    debug_execute(gc.decompose, ['angle_bisector_determination_angle_equal(M,i,x,a)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(x,i,i,a)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(M,x,i,a)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(i,a,c,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(i,c,a)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(i,c,m)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(i,m,c,m)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(i,m)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_perpendicular(H,i,M,a,N,m,P,n)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_multiple_forms(H,P,n,M,a,N,m)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(n,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(d,n,n,d)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(C,d,X,n,M,a,A,d,X,n,M,k)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(M,a,C,d,X,n,M,k,A,d,X,n)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_asa(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(n,a,k,n)'])
    debug_execute(gc.decompose, ['triangle_determination(X,d,A,k,M,n)'])
    debug_execute(gc.decompose, ['triangle_determination(X,n,M,a,C,d)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(n,k)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,n)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(a,n,n,k)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_sss(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.decompose, ['triangle_determination(A,p,P,n,M,k)'])
    debug_execute(gc.decompose, ['triangle_determination(C,a,M,n,P,g)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(M,P,M,P)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(C,M,A,M)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(m,c)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(c,m,m,c)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(A,c,Y,m,N,l,D,c,Y,m,N,a)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(N,l,A,c,Y,m,N,a,D,c,Y,m)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_asa(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(m,l,a,m)'])
    debug_execute(gc.decompose, ['triangle_determination(Y,c,D,a,N,m)'])
    debug_execute(gc.decompose, ['triangle_determination(Y,m,N,l,A,c)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(m,a)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(l,m)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(l,m,m,a)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_sss(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.decompose, ['triangle_determination(D,h,P,m,N,a)'])
    debug_execute(gc.decompose, ['triangle_determination(A,l,N,m,P,p)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(A,N,D,N)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(N,P,N,P)'])
    debug_execute(gc.decompose, ['point_on_circle_determination_concyclic(Φ,F,B,E,T)'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_inscribed_angle_sum(F,e,B,f,E,x,T,y)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Φ,F,e,B,f,E,p)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(F,e,B,f,E,p)'])
    debug_execute(gc.decompose, ['triangle_determination(F,e,B,f,E,p)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(l,y,x,y)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(l,x,y)'])
    debug_execute(gc.decompose, ['parallel_property_multiple_forms(x,l)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(N,l,a,y)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,l)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,y)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(y,a,k,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(y,k,a)'])
    debug_execute(gc.decompose, ['concyclic_between_points_property_inscribed_angle_equal(B,w,A,c,D,e,F,p)'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_same_circle(Γ,B,A,D,F)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(D,c,a,w)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(D,a,K,v,A,c)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(D,w,B,v,K,a)'])
    debug_execute(gc.decompose, ['triangle_determination(D,a,K,v,A,c)'])
    debug_execute(gc.decompose, ['triangle_determination(D,w,B,v,K,a)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(w,v,v,c)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(D,w,B,v,A,c)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(D,w,B,v,A,c)'])
    debug_execute(gc.decompose, ['triangle_determination(D,w,B,v,A,c)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_distance_equal(a,v,B,A,D)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_multiple_forms(a,v,A,B)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,f)'])
    debug_execute(gc.decompose, ['concyclic_between_points_property_inscribed_angle_sum(B,u,C,d,A,p,E,f)'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_same_circle(Ω,B,C,A,E)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(C,u,a,d)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(B,u,C,a,K,v)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(A,v,K,a,C,d)'])
    debug_execute(gc.decompose, ['triangle_determination(B,u,C,a,K,v)'])
    debug_execute(gc.decompose, ['triangle_determination(A,v,K,a,C,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(d,v,v,u)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(C,d,A,v,B,u)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(C,d,A,v,B,u)'])
    debug_execute(gc.decompose, ['triangle_determination(C,d,A,v,B,u)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_distance_equal(a,v,A,B,C)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(v,a)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(a,v)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_multiple_forms(a,v)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_perpendicular_between_line(a,v,A,B)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_determination_center_line_and_common_chord(Ω,Γ,M,N,a,A,B,v)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(x,l,p)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(x,p,l,p)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,l)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,x)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(y,k,p)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(y,p,k,p)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(D,c,a,h)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(A,p,l,c)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(A,d,k,p)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(C,g,a,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(y,p,p,l)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(N,y,F,p,A,l)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(N,y,F,p,A,l)'])
    debug_execute(gc.decompose, ['triangle_determination(N,y,F,p,A,l)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(N,F,N,A)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(l,c,c,a)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['triangle_determination(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(N,A,N,D)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Γ,N,F)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Γ,N,D)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Γ,N,A)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(k,p,p,x)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(M,k,A,p,E,x)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(M,k,A,p,E,x)'])
    debug_execute(gc.decompose, ['triangle_determination(M,k,A,p,E,x)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(M,A,M,E)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(a,d,d,k)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['triangle_determination(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(M,C,M,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Ω,M,E)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Ω,M,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Ω,M,C)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(g,a,a,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(P,g,C,a,D,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(P,g,C,a,D,h)'])
    debug_execute(gc.decompose, ['triangle_determination(P,g,C,a,D,h)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(P,C,P,D)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(p,c,c,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(P,p,A,c,D,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(P,p,A,c,D,h)'])
    debug_execute(gc.decompose, ['triangle_determination(P,p,A,c,D,h)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(P,A,P,D)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(g,d,d,p)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(P,g,C,d,A,p)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(P,g,C,d,A,p)'])
    debug_execute(gc.decompose, ['triangle_determination(P,g,C,d,A,p)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(P,C,P,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Δ,P,D)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Δ,P,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Δ,P,C)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Δ,D,a,C,d,A,c)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.decompose, ['circumcenter_of_triangle_property_center_of_circle(P,Δ,C,d,A,c,D,a)'])
    debug_execute(gc.decompose, ['arc_property_central_angle_and_inscribed_angle(Φ,G,E,T,F,o,b,p,y)'])
    debug_execute(gc.decompose, ['arc_property_central_angle_and_inscribed_angle(Φ,G,T,F,E,b,q,x,p)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(y,x)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(x,a,l,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(x,l,a)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,k)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,b)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(G,b,Q,p,E,o)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(G,q,F,p,Q,b)'])
    debug_execute(gc.decompose, ['triangle_determination(G,b,Q,p,E,o)'])
    debug_execute(gc.decompose, ['triangle_determination(G,q,F,p,Q,b)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(q,b)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(b,o)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(q,p,p,o)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(G,q,F,p,E,o)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(G,q,F,p,E,o)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(G,F,G,E)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Φ,G,E)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Φ,G,F)'])
    debug_execute(gc.decompose, ['triangle_determination(G,q,F,p,E,o)'])

    gc.show_gc()
    gc.draw_sg()


def test_imo_2025_p2_auto():
    parsed_gdl = parse_gdl(load_json('../../../data/gdl-xiaokai.json'))
    gc = test_imo_2025_p2_gc()

    while True:
        for theorem in parsed_gdl['Theorems']:
            debug_execute(gc.apply, [theorem])
        if gc.status_of_goal[0] == 1:
            break

    gc.show_gc()
    gc.draw_sg()


def test_yuchang():
    problem = GeometricConfiguration(parse_gdl(load_json('../../../data/gdl/gdl-yuchang.json')))
    for i in load_json('../../../data/gc/gc-yuchang.json')['15']["constructions"]:
        problem.construct(i)

    #####目标：证明∠APM=∠ADC#####
    debug_execute(problem.apply, ["extends_re_LinesPerpendicular_1(i,a)"])
    # 1.LinesPerpendicular(a,i)
    debug_execute(problem.apply, ["D55(A,C,P,I,a,i)"])
    # 2.SegmentEqualSegment(C,P,A,P)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_1(C,P,A,P)"])
    # 3.SegmentEqualSegment(P,C,A,P)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(P,C,A,P)"])
    # 4.SegmentEqualSegment(A,P,P,C)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_1(A,P,P,C)"])
    # 5.SegmentEqualSegment(P,A,P,C)
    debug_execute(problem.apply, ["B7(A,C,P,𝓬,m,a)"])
    # 6.Triangle(A,P,C,𝓬,a,m)
    debug_execute(problem.apply, ["D46(A,C,P,𝓬,m,a)"])
    # 7.AngleEqualAngle(m,a,a,𝓬) 即∠CAP=∠ACP
    debug_execute(problem.apply, ["extends_re_AngleEqualAngle_3(m,a,a,𝓬)"])
    # 7_1.Eq(Sub(ma.ma,a𝓬.ma))
    debug_execute(problem.apply, ["B6(A,P,I,i,a,m)"])
    # 8.ClockwiseTriangle(A,P,I,i,a,m)
    debug_execute(problem.apply, ["B1(A,P,I,i,a,m)"])
    # 9.Eq(Sub(Add(im.ma,ai.ma,ma.ma),180))
    debug_execute(problem.apply, ["B6(C,I,P,i,𝓬,a)"])
    # 10.ClockwiseTriangle(C,I,P,i,𝓬,a)
    debug_execute(problem.apply, ["B1(C,I,P,i,𝓬,a)"])
    # 11.Eq(Sub(Add(ia.ma,𝓬i.ma,a𝓬.ma),180))
    debug_execute(problem.apply, ["extends_re_LinesPerpendicular_2(a,i)"])
    # 12.Eq(Sub(ai.ma,90))"
    debug_execute(problem.apply, ["extends_re_LinesPerpendicular_2(i,a)"])
    # 12.Eq(Sub(ia.ma,90))"
    debug_execute(problem.apply, ["A8(i,a,a,i)"])
    # 13.AngleEqualAngle(i,a,a,i)
    debug_execute(problem.apply, ["extends_re_AngleEqualAngle_3(i,a,a,i)"])
    # 13_1.Eq(Sub(ia.ma,ai.ma))
    debug_execute(problem.apply, ["A8(i,m,𝓬,i)"])
    # 15.AngleEqualAngle(i,m,𝓬,i)
    debug_execute(problem.apply, ["extends_re_AngleEqualAngle_3(i,m,𝓬,i)"])
    # 16."Eq(Sub(im.ma,𝓬i.ma))"
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(C,J,D,J)"])
    # 17.SegmentEqualSegment(D,J,C,J)
    debug_execute(problem.apply, ["extends_re_LinesPerpendicular_1(j,l)"])
    # 18.LinesPerpendicular(j,l)
    debug_execute(problem.apply, ["D55(D,C,P,J,l,j)"])
    # 19.SegmentEqualSegment(C,P,D,P)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_1(C,P,D,P)"])
    # 20.SegmentEqualSegment(P,C,D,P)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(P,C,D,P)"])
    # 21.SegmentEqualSegment(D,P,P,C)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_1(D,P,P,C)"])
    # 22.SegmentEqualSegment(P,D,P,C)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(P,D,P,C)"])
    # 23.SegmentEqualSegment(P,C,P,D)
    debug_execute(problem.apply, ["B7(C,D,P,𝓭,𝓬,l)"])
    # 24.Triangle(C,P,D,𝓭,l,𝓬)
    debug_execute(problem.apply, ["D46(C,D,P,𝓭,𝓬,l)"])
    # 25.AngleEqualAngle(𝓬,l,l,𝓭)
    debug_execute(problem.apply, ["extends_re_AngleEqualAngle_3(𝓬,l,l,𝓭)"])
    # 25_1."Eq(Sub(𝓬l.ma,l𝓭.ma))"
    debug_execute(problem.apply, ["D25(A,P,P,C,D,P)"])
    # 26.SegmentEqualSegment(A,P,D,P)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_1(A,P,D,P)"])
    # 27.SegmentEqualSegment(P,A,D,P)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(P,A,D,P)"])
    # 28.SegmentEqualSegment(D,P,P,A)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_1(D,P,P,A)"])
    # 29.SegmentEqualSegment(P,D,P,A)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(P,D,P,A)"])
    # 30.SegmentEqualSegment(P,A,P,D)
    debug_execute(problem.apply, ["B7(A,D,P,𝓭,m,b)"])
    # 31.Triangle(A,P,D,𝓭,b,m)
    debug_execute(problem.apply, ["D46(A,D,P,𝓭,m,b)"])
    # 32.AngleEqualAngle(m,b,b,𝓭)
    debug_execute(problem.apply, ["extends_re_AngleEqualAngle_3(m,b,b,𝓭)"])
    # 32_1."Eq(Sub(mb.ma,b𝓭.ma))"
    debug_execute(problem.apply, ["B6(A,D,C,l,a,b)"])
    # 33.ClockwiseTriangle(A,D,C,l,a,b)
    debug_execute(problem.apply, ["B1(A,D,C,l,a,b)"])
    # 34.Eq(Sub(Add(lb.ma,al.ma,ba.ma),180))
    debug_execute(problem.apply, ["B6(A,P,C,𝓬,a,m)"])
    # 35.ClockwiseTriangle(A,P,C,𝓬,a,m)
    debug_execute(problem.apply, ["B1(A,P,C,𝓬,a,m)"])
    # 36.Eq(Sub(Add(𝓬m.ma,a𝓬.ma,ma.ma),180))
    debug_execute(problem.apply, ["A16_1(D,𝓭,l,b)"])
    # 37."Eq(Sub(Add(𝓭l.ma,lb.ma),𝓭b.ma))"
    debug_execute(problem.apply, ["A16_1(C,a,l,𝓬)"])
    # 38."Eq(Sub(Add(al.ma,l𝓬.ma),a𝓬.ma))"
    debug_execute(problem.apply, ["A16_1(A,b,m,a)"])
    # 39."Eq(Sub(Add(bm.ma,ma.ma),ba.ma))"
    debug_execute(problem.apply, ["A16_1(P,𝓬,i,m)"])
    # 40."Eq(Sub(Add(𝓬i.ma,im.ma),𝓬m.ma))"
    debug_execute(problem.apply, ["B6(A,D,P,𝓭,m,b)"])
    # 40.ClockwiseTriangle(A,P,D,𝓭,b,m)
    debug_execute(problem.apply, ["B1(A,D,P,𝓭,m,b)"])
    # 41.Eq
    debug_execute(problem.apply, ["B6(C,D,P,𝓭,𝓬,l)"])
    # 42.ClockwiseTriangle(C,D,P,𝓭,𝓬,l)
    debug_execute(problem.apply, ["B1(C,D,P,𝓭,𝓬,l)"])
    # 43.Eq
    debug_execute(problem.apply, ["A17(l,𝓭)"])
    #
    debug_execute(problem.apply, ["A17(l,𝓬)"])
    #
    debug_execute(problem.apply, ["A17(m,b)"])
    #
    debug_execute(problem.apply, ["A17(b,𝓭)"])
    #
    debug_execute(problem.apply, ["A8(i,m,l,b)"])
    # 44.AngleEqualAngle(i,m,l,b)
    debug_execute(problem.apply, ["extends_re_AngleEqualAngle_3(i,m,l,b)"])
    # 45."Eq(Sub(im.ma,lb.ma))"
    #####目标：证明∠APM=∠ADC完成#####

    #####目标：证明∠AEC=∠CMI#####
    debug_execute(problem.apply, ["DcheckCircle(U,A,M)"])
    debug_execute(problem.apply, ["DcheckCircle(U,C,M)"])
    debug_execute(problem.apply, ["A7(A,M,C,M)"])
    # 46.SegmentEqualSegment(A,M,C,M)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(A,M,C,M)"])
    # 46.SegmentEqualSegment(C,M,A,M)
    debug_execute(problem.apply, ["extends_re_SegmentEqualSegment_2(A,I,C,I)"])
    # 47.SegmentEqualSegment(C,I,A,I)
    debug_execute(problem.apply, ["D56(A,C,M,I,a,𝓰)"])
    # 48.LinesPerpendicular(a,𝓰)
    debug_execute(problem.apply, ["extends_re_LinesPerpendicular_1(a,𝓰)"])
    # 48.LinesPerpendicular(𝓰,a)
    debug_execute(problem.apply, ["D9(𝓰,a,i)"])
    # 49.LinesParallel(𝓰,i)
    debug_execute(problem.apply, ["extends_re_LinesParallel_1(𝓰,i)"])
    # 49.LinesParallel(i,𝓰)
    debug_execute(problem.apply, ["D66(I,i,𝓰)"])


if __name__ == '__main__':
    # test_imo_2025_p2_gc()
    # test_imo_2025_p2_forward()
    # test_imo_2025_p2_backward()
    # test_imo_2025_p2_auto()
    test_yuchang()
