import json
import pandas as pd


def process_hypergraph_to_excel(json_file_path, output_excel_path):
    # 1. 读取 JSON 文件
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        # 处理某些json结构可能包含在外层字典的情况，如 prompt 中的 fullContent
        if 'fullContent' in data:
            data = data['fullContent']

    notes = data.get('notes', [])
    deps = data.get('dependent_entities', [])
    edges = data.get('edges', [])
    hypergraph = data.get('hypergraph', [])

    # --- 准备工作：建立索引映射 ---

    # 将 notes 转换为字符串形式，方便阅读
    note_str_map = {i: str(n).replace("'", "") for i, n in enumerate(notes)}
    edge_str_map = {i: str(e).replace("'", "") for i, e in enumerate(edges)}

    # 预处理 Hypergraph 以便反向查找 (Child -> Created By)
    # 结构: note_index -> {'edge_id': int, 'edge_content': str, 'parents': list}
    note_provenance = {}

    # 准备 Sheet 2: Logic_Flow (推导过程) 的数据
    flow_rows = []

    for step_idx, step in enumerate(hypergraph):
        # step 结构通常为: [parent_indices_list, edge_index, child_indices_list]
        parent_idxs = step[0]
        edge_idx = step[1]
        child_idxs = step[2]

        edge_content = edge_str_map.get(edge_idx, "Unknown Edge")

        # 记录逻辑流数据
        parent_contents = [note_str_map.get(pid, f"ID_{pid}") for pid in parent_idxs]
        child_contents = [note_str_map.get(cid, f"ID_{cid}") for cid in child_idxs]

        flow_rows.append({
            'Step ID': step_idx,
            'Parent Notes (Content)': " AND ".join(parent_contents),
            'Applied Rule (Edge)': edge_content,
            'Generated Children (Content)': " AND ".join(child_contents),
            'Parent IDs': str(parent_idxs),
            'Rule ID': edge_idx,
            'Children IDs': str(child_idxs)
        })

        # 记录反向查找数据 (每个子节点是由哪个 Step 生成的)
        for child_id in child_idxs:
            note_provenance[child_id] = {
                'edge_id': edge_idx,
                'edge_content': edge_content,
                'parent_ids': parent_idxs
            }

    # --- 准备 Sheet 1: Notes_Detail (事实详情) ---
    note_rows = []
    for i, content in enumerate(notes):
        # 获取依赖项
        current_deps = deps[i] if i < len(deps) else []

        # 获取来源信息 (如果是初始条件，则没有 provenance)
        prov = note_provenance.get(i, {})
        source_rule = prov.get('edge_content', 'Given / Initial')
        source_rule_id = prov.get('edge_id', '-')
        parent_ids = prov.get('parent_ids', [])

        note_rows.append({
            'Note ID': i,
            'Content (Fact)': str(content).replace("'", ""),
            'Dependent IDs': str(current_deps),
            'Generated By Rule (Content)': source_rule,
            'Generated By Rule (ID)': source_rule_id,
            'Derived From Parent IDs': str(parent_ids)
        })

    # --- 准备 Sheet 3: Edges_List ---
    edge_rows = []
    for i, content in enumerate(edges):
        edge_rows.append({
            'Edge ID': i,
            'Rule Content': str(content).replace("'", "")
        })

    # --- 创建 DataFrame ---
    df_notes = pd.DataFrame(note_rows)
    df_flow = pd.DataFrame(flow_rows)
    df_edges = pd.DataFrame(edge_rows)

    # --- 写入 Excel ---
    try:
        with pd.ExcelWriter(output_excel_path, engine='openpyxl') as writer:
            df_notes.to_excel(writer, sheet_name='1. Notes_Detail', index=False)
            df_flow.to_excel(writer, sheet_name='2. Logic_Flow (Hypergraph)', index=False)
            df_edges.to_excel(writer, sheet_name='3. Edges_Reference', index=False)

            # 简单的列宽调整 (可选)
            for sheet in writer.sheets.values():
                for col in sheet.column_dimensions:
                    sheet.column_dimensions[col].width = 25

        print(f"成功！文件已生成: {output_excel_path}")
        print(f"包含事实数: {len(df_notes)}, 推导步数: {len(df_flow)}")

    except Exception as e:
        print(f"保存 Excel 时出错: {e}")


# --- 执行 ---
# 请确保文件名与你的json文件一致
json_filename = 'data/hypergraph-2-solve.json'
excel_filename = 'excel_data/geometry_proof_analysis-2.xlsx'


if __name__ == '__main__':
    # 简单的检查文件是否存在，防止报错
    import os

    if os.path.exists(json_filename):
        process_hypergraph_to_excel(json_filename, excel_filename)
    else:
        print(f"未找到文件: {json_filename}，请确认路径或文件名。")